local fzf = require("fzf-lua")
vim.keymap.set("n", "<leader>ff", fzf.files, {})
vim.keymap.set("n", "<leader>fg", fzf.live_grep, {})
vim.keymap.set("n", "<leader>fb", fzf.buffers, {})
vim.keymap.set("n", "<leader>fd", fzf.lsp_document_diagnostics, {})
vim.keymap.set("n", "<leader>gg", fzf.git_files, {})
